### ISSUE TITLE
Integrate child module design

### ISSUE THREAD

**Issue by eddie-knight** [finos/terraform-aws-cfi-eks#7]
We should be extracting key resources from this repo, following the documentation here:

https://github.com/finos/compliant-financial-infrastructure/blob/dev/docs/terraform-module-best-practices.md

The child modules should be cloned from the template repo here:

https://github.com/finos/cfi-terraform-template-child-module

List of child modules to be created (needs edited):

- [x] AWS EKS Cluster (without peripherals)

**Comment by eddie-knight** [comment]
Added a request to create the child module repo for AWS EKS cluster here:

https://github.com/finos/cfi-terraform-template-child-module

**Comment by ml4** [comment]
Discussing with @eddie-knight:

Broadly speaking, we think, define VPC as a mod with all the features one'd want, with switches in the resources for `count` so that if var true then deploy element else don't. This provides flexibility for members deploying a VPC but who dont want routing and subnets with it for instance.  Example

```hcl
resource "aws_subnet" "main" {
  count = var.add_subnets == true ? var.num_subnets : 0
...
```
etc.

In my VPC, I have:
```
aws_default_security_group
aws_security_group
aws_network_acl

aws_eip
aws_internet_gateway
aws_nat_gateway
aws_route
aws_route_table
aws_route_table_association

aws_subnet
aws_vpc
aws_vpc_endpoint
aws_vpc_endpoint_route_table_association
```
split into security, routing and core. We would need to associate groups of resources to need so eg no point having a switch allowing a user to not have an endpoint resource, but still have an endpoint route table association.

I think also SSH key and VPC peering mods.

**Comment by thinkl33t** [comment]
Moved conversation above into CFI issue @ https://github.com/finos/compliant-financial-infrastructure/issues/343

**Comment by thinkl33t** [comment]
Initial issue topic has been done, closing
